[package]
name = "chonk"
version = "0.1.0"
description = "The Chonk programming language"
readme = "README.md"
keywords = ["chonk", "programming", "language"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
